// server/scripts/generate.js
// Headless end-to-end run of the autonomous pipeline from a single prompt.
//   node scripts/generate.js "a space shooter where you dodge asteroids"
// Exit code 0 only if Gemini produced the game AND it passed the playtest suite.

import '../loadEnv.js';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import { fileURLToPath } from 'url';
import { runPipeline, getJob } from '../services/pipeline.js';
import { initJob, registerClient } from '../utils/logger.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const prompt = process.argv.slice(2).join(' ').trim();
if (prompt.length < 5) {
  console.error('Usage: node scripts/generate.js "<game description>"');
  process.exit(2);
}

const COLORS = { stage: '\x1b[36m', success: '\x1b[32m', error: '\x1b[31m', warning: '\x1b[33m', test: '\x1b[35m' };
const jobId = uuidv4();
initJob(jobId);

let completeEvent = null;
let geminiUsed = false;
const origLog = console.log;
console.log = (...args) => {
  if (String(args[0]).startsWith('[Gemini] ✓')) geminiUsed = true;
  origLog(...args);
};

registerClient(jobId, {
  write(payload) {
    const ev = JSON.parse(payload.replace(/^data: /, ''));
    if (ev.type === 'pipeline_complete') completeEvent = ev;
    if (['spec', 'code_ready', 'test_result'].includes(ev.type)) return;
    const c = COLORS[ev.type] || '';
    origLog(`${c}[${ev.type}]\x1b[0m ${ev.message}`);
  },
});

console.log(`\n▶ Prompt: "${prompt}"\n▶ Job: ${jobId}\n▶ Model: ${process.env.GEMINI_MODEL || 'gemini-3.8-flash'}\n`);
const t0 = Date.now();
await runPipeline(jobId, prompt, 'cli', { maxHealRetries: Number(process.env.MAX_HEALS || 4) });
const job = getJob(jobId);

const file = path.join(__dirname, '..', 'games', `${jobId}_v${job.attempt}.html`);
const ok = job.status === 'complete' && !job.usedFallback && geminiUsed;
origLog('\n──────── RESULT ────────');
origLog(`status:        ${job.status}`);
origLog(`title:         ${job.spec?.title}`);
origLog(`builds:        ${job.attempt}  (heal cycles: ${job.healCycles})`);
origLog(`gemini used:   ${geminiUsed}`);
origLog(`used template: ${job.usedFallback}`);
origLog(`elapsed:       ${((Date.now() - t0) / 1000).toFixed(1)}s`);
origLog(`game file:     ${file}`);
if (completeEvent?.bugsFixed?.length) {
  origLog('bugs fixed:');
  for (const b of completeEvent.bugsFixed) origLog(`  - cycle ${b.cycle}: [${b.failedAssertions.join(', ')}] ${String(b.diagnosis).slice(0, 160).replace(/\s+/g, ' ')}`);
}
origLog(ok ? '\x1b[32m✔ VERIFIED PLAYABLE (generated by Gemini)\x1b[0m' : '\x1b[31m✘ NOT VERIFIED\x1b[0m');
process.exit(ok ? 0 : 1);
